name: real-estate-watchdog

services:
  minio:
    image: minio/minio:latest
    container_name: lakehouse-minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Webové rozhraní
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: amazon/aws-cli:latest
    container_name: lakehouse-minio-init
    depends_on:
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "sleep 5 && aws --endpoint-url http://minio:9000 s3 mb s3://warehouse || true"

  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    container_name: lakehouse-nessie
    ports:
      - "19120:19120"
    environment:
      - QUARKUS_HTTP_PORT=19120
      - nessie.catalog.default-warehouse=default
      - nessie.catalog.warehouses.default.location=s3://warehouse/
      - nessie.catalog.service.s3.default-options.endpoint=http://minio:9000
      - nessie.catalog.service.s3.default-options.region=us-east-1
      - nessie.catalog.service.s3.default-options.path-style-access=true
      - nessie.catalog.service.s3.default-options.auth-type=STATIC
      - nessie.catalog.service.s3.default-options.access-key=urn:nessie-secret:quarkus:nessie.catalog.secrets.access-key
      - nessie.catalog.secrets.access-key.name=admin
      - nessie.catalog.secrets.access-key.secret=password
volumes:
  minio_data: